services:
  ai-report-generator:
    build: .
    ports:
      - "8888:8888"
    environment:
      - DEBUG=False
      - HOST=0.0.0.0
      - PORT=8888
      # DATABASE_URL and other secrets will be injected by Railway from environment variables
      # For local development, you can create a .env file
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - ai-report-network

networks:
  ai-report-network:
    driver: bridge
