services:
  ai-report-generator:
    build: .
    ports:
      - "8888:8888"
    env_file:
      - .env
    environment:
      - DEBUG=False
      - HOST=0.0.0.0
      - PORT=8888
      # DATABASE_URL will be read from .env file or Railway environment variables
      # If not set, it will default to sqlite:///./ai_report.db as defined in app/db/session.py
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - ai-report-network

networks:
  ai-report-network:
    driver: bridge
